version: '3.8'

services:
  # api:
  #   image: biblebee/api:v1.0.0
  #   ports:
  #     - 8000:8000
  #   command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker biblebee_api:app -b 0.0.0.0:8000
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   volumes:
  #     - ./resource/:/app/resource
  #   depends_on:
  #     - redis

  worker:
    image: biblebee/api:v1.0.0
    command: celery -A biblebee_api.worker.celery worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - ./resource/:/app/resource
    depends_on:
      # - api
      - redis

  # scheduler:
  #   image: biblebee/api:v1.0.0
  #   command: celery -A biblebee_api.scheduler beat
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - worker

  redis:
    image: redis:7
    ports:
      - 6379:6379
