version: '3.8'

services:
  api:
    image: biblebee/api:v1.0.1
    ports:
      - 8000:8000
    command: gunicorn -w 1 -k uvicorn.workers.UvicornWorker biblebee_api:app -b 0.0.0.0:8000
    environment:
      - FIREBASE_CONFIG_FILE=/run/secrets/firebase_config
      - DB_PATH=/app/resource/Bibles.sqlite3
      - CELERY_BROKER_URL=celery_broker_url
      - CELERY_RESULT_BACKEND=celery_result_backend
    volumes:
      - ./resource:/app/resource
    secrets:
      - firebase_config
      - celery_broker_url
      - celery_result_backend
  worker:
    image: biblebee/api:v1.0.1
    command: celery -A biblebee_api.worker.celery worker --loglevel=info
    volumes:
      - ./resource/:/app/resource
    environment:
      - CELERY_BROKER_URL=celery_broker_url
      - CELERY_RESULT_BACKEND=celery_result_backend
    depends_on:
      - api
    secrets:
      - celery_broker_url
      - celery_result_backend

  scheduler:
    image: biblebee/api:v1.0.1
    command: celery -A biblebee_api.scheduler beat
    environment:
      - CELERY_BROKER_URL=celery_broker_url
      - CELERY_RESULT_BACKEND=celery_result_backend
    depends_on:
      - worker
    secrets:
      - celery_broker_url
      - celery_result_backend

secrets:
  firebase_config:
    file: config/firebase.json
  celery_broker_url:
    external: true
    name: '${CELERY_BROKER_URL}'
  celery_result_backend:
    external: true
    name: '${CELERY_RESULT_BACKEND}'
